// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-wGoSP0Xb4hTFCXSTShfMwE2-fkv9p-o',
    appId: '1:446170854241:web:e91e53635f29fbd5db4b20',
    messagingSenderId: '446170854241',
    projectId: 'myfinanceassistant-268ac',
    authDomain: 'myfinanceassistant-268ac.firebaseapp.com',
    storageBucket: 'myfinanceassistant-268ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb5sW0uz1F5rxyuq8WNHkwL8VdyQ0YYt8',
    appId: '1:446170854241:android:e4760943d12606cfdb4b20',
    messagingSenderId: '446170854241',
    projectId: 'myfinanceassistant-268ac',
    storageBucket: 'myfinanceassistant-268ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPS9t-aXtIgO2D72BO1oKPnp4MBvCsgvw',
    appId: '1:446170854241:ios:a44d43452dbb063adb4b20',
    messagingSenderId: '446170854241',
    projectId: 'myfinanceassistant-268ac',
    storageBucket: 'myfinanceassistant-268ac.firebasestorage.app',
    iosBundleId: 'com.lazypanda.myfinanceassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPS9t-aXtIgO2D72BO1oKPnp4MBvCsgvw',
    appId: '1:446170854241:ios:a44d43452dbb063adb4b20',
    messagingSenderId: '446170854241',
    projectId: 'myfinanceassistant-268ac',
    storageBucket: 'myfinanceassistant-268ac.firebasestorage.app',
    iosBundleId: 'com.lazypanda.myfinanceassistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-wGoSP0Xb4hTFCXSTShfMwE2-fkv9p-o',
    appId: '1:446170854241:web:5bbb5cb34b472d57db4b20',
    messagingSenderId: '446170854241',
    projectId: 'myfinanceassistant-268ac',
    authDomain: 'myfinanceassistant-268ac.firebaseapp.com',
    storageBucket: 'myfinanceassistant-268ac.firebasestorage.app',
  );
}
